baseURL = "https://kevinbest0702.github.io/xtxb.me/" 
languageCode = "zh-CN"
title = "Kevin's Blog" # 修改“”中的内容为自己的网站名字
theme = "hyde" # 如果以后启用其它主题，在这里替换主题名字
disqusShortname = "" # 如果使用 disqus 评论系统，在这里填写自己的 disqus 用户名 
hasCJKLanguage = true
enableEmoji = true

[permalinks]
  posts = "/:filename"

[Menus] # 边栏目录
  main = [
      {Name = "Archives", URL = "https://kevinbest0702.github.io/xtxb.me/posts/"},
      {Name = "Tags", URL = "https://kevinbest0702.github.io/xtxb.me/tags/"},
      {Name = "Photos", URL = "https://kevinbest0702.github.io/xtxb.me/photos/"}
  ]

[params] # 指定发布的文件目录和博客描述
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "content/posts"
  # description abou this website
  description = "There is only one thing in the world worse than being talked about, and that is not being talked about."

[params.valine] # 我把它默认甚至为关闭了，想打开可以修改 false 为 true，填写 valine 的 appId 和 appKey 即可开启 valine 的评论系统。（目前 valine 好评在下降，很多人更换了自己的评论系统，我还没有折腾，暂时不提供这部分教程了。想用的可以参考 <https://valine.js.org/> 操作手册）
  enable = false
    appId = ''
    appKey = ''
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true